### ISSUE TITLE
Add ability to specify line numbers

### ISSUE THREAD

**Issue by janko-m** [matflores/protest#10]
I would like to add a feature for specifying line numbers, which gives the ability to run a single test or a subset of tests. The behaviour would be the following:

```rb
Protest.describe "My Test" do # specifying this line would run the whole describe block
  context "my context" do # specifying this line would the whole context block
    test "my test 1" do #
      # ...             # specifying any of these 3 lines would run "test 1"
    end                 # 

    test "my test 2" do #
      # ...             # specifying any of these 3 lines would run "test 2"
    end                 #
  end
end
```

This is intended to be added on top of the `protest` command-line interface suggested in https://github.com/matflores/protest/pull/9. @matflores the only thing I'm struggling with is deciding which syntax to use, this:

```
$ protest test/something_test.rb --line 15
```

or this:

```
$ protest test/something_test.rb:15
```

**Comment by matflores** [comment]
@janko-m thanks!

> the only thing I'm struggling with is deciding which syntax to use, this:

```
$ protest test/something_test.rb --line 15
```

or this:

```
$ protest test/something_test.rb:15
```

The second one 👍
